<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>Plutao</AssemblyName>
    <RootNamespace>Plutao</RootNamespace>
    <Version>0.5.7</Version>
    <ApplicationIcon Condition="Exists('plutao.ico')">plutao.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
